-- Seed 60 demo candidates across roles, countries, and experience levels
-- Tagged with is_demo via match_tags so they can be filtered later

INSERT INTO candidates (user_id, full_name, email, headline, bio, country, city, skills, experience_years, education, work_history, languages, visa_status, match_tags, is_public, remote_preference, available_now)
VALUES
-- ── Engineering ──
('00000000-0000-0000-0000-000000000001', 'Sophia Chen', 'sophia.chen@demo.io', 'Senior Full-Stack Engineer | React & Node.js', 'I build scalable web apps with a focus on clean architecture and great UX. 7 years shipping production code at startups and Fortune 500 companies.', 'us', 'San Francisco', ARRAY['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'AWS', 'GraphQL', 'Docker', 'Kubernetes'], 7, '[{"institution":"Stanford University","degree":"M.S.","field":"Computer Science","end_year":2017}]'::jsonb, '[{"company":"Stripe","title":"Senior Engineer","start_date":"2021-01","is_current":true},{"company":"Uber","title":"Software Engineer","start_date":"2017-06","end_date":"2020-12","is_current":false}]'::jsonb, ARRAY['English', 'Mandarin'], 'citizen', ARRAY['remote', 'startup', 'quality', 'ship', 'demo'], true, 'remote', true),

('00000000-0000-0000-0000-000000000002', 'Marcus Johnson', 'marcus.j@demo.io', 'Backend Engineer | Python & Go Microservices', 'Distributed systems enthusiast. Led migration from monolith to microservices serving 10M+ users. Open source contributor.', 'us', 'Austin', ARRAY['Python', 'Go', 'Kubernetes', 'gRPC', 'Redis', 'PostgreSQL', 'Terraform', 'CI/CD'], 6, '[{"institution":"Georgia Tech","degree":"B.S.","field":"Computer Science","end_year":2018}]'::jsonb, '[{"company":"Datadog","title":"Backend Engineer","start_date":"2020-03","is_current":true},{"company":"DigitalOcean","title":"Software Engineer","start_date":"2018-07","end_date":"2020-02","is_current":false}]'::jsonb, ARRAY['English'], 'citizen', ARRAY['remote', 'autonomy', 'quality', 'demo'], true, 'remote', true),

('00000000-0000-0000-0000-000000000003', 'Priya Patel', 'priya.p@demo.io', 'Frontend Engineer | React & Design Systems', 'Passionate about accessible, beautiful interfaces. Built and maintained design systems used by 200+ developers.', 'gb', 'London', ARRAY['React', 'TypeScript', 'CSS', 'Figma', 'Storybook', 'Testing Library', 'Next.js', 'Tailwind CSS'], 5, '[{"institution":"Imperial College London","degree":"M.Eng","field":"Computing","end_year":2019}]'::jsonb, '[{"company":"Deliveroo","title":"Frontend Engineer","start_date":"2021-01","is_current":true},{"company":"BBC","title":"Junior Developer","start_date":"2019-09","end_date":"2020-12","is_current":false}]'::jsonb, ARRAY['English', 'Hindi', 'Gujarati'], 'citizen', ARRAY['hybrid', 'team', 'quality', 'coaching', 'demo'], true, 'hybrid', true),

('00000000-0000-0000-0000-000000000004', 'Erik Lindqvist', 'erik.l@demo.io', 'DevOps Engineer | AWS & Infrastructure Automation', 'Infrastructure nerd who loves making deployments boring. GitOps evangelist. 99.99% uptime track record.', 'se', 'Stockholm', ARRAY['AWS', 'Terraform', 'Kubernetes', 'Docker', 'GitHub Actions', 'Prometheus', 'Grafana', 'Linux'], 8, '[{"institution":"KTH Royal Institute","degree":"M.S.","field":"Computer Science","end_year":2016}]'::jsonb, '[{"company":"Spotify","title":"Senior DevOps Engineer","start_date":"2019-06","is_current":true},{"company":"Ericsson","title":"Cloud Engineer","start_date":"2016-09","end_date":"2019-05","is_current":false}]'::jsonb, ARRAY['Swedish', 'English'], 'citizen', ARRAY['remote', 'autonomy', 'quality', 'demo'], true, 'remote', false),

('00000000-0000-0000-0000-000000000005', 'Ana Santos', 'ana.s@demo.io', 'Mobile Developer | React Native & iOS', 'Shipped 12 apps with 5M+ combined downloads. Love crafting smooth mobile experiences.', 'br', 'São Paulo', ARRAY['React Native', 'Swift', 'TypeScript', 'Firebase', 'GraphQL', 'Jest', 'Detox', 'App Store Connect'], 4, '[{"institution":"USP","degree":"B.S.","field":"Computer Engineering","end_year":2020}]'::jsonb, '[{"company":"Nubank","title":"Mobile Developer","start_date":"2021-02","is_current":true},{"company":"iFood","title":"Junior Developer","start_date":"2020-03","end_date":"2021-01","is_current":false}]'::jsonb, ARRAY['Portuguese', 'English', 'Spanish'], 'needs_sponsorship', ARRAY['remote', 'startup', 'ship', 'demo'], true, 'remote', true),

('00000000-0000-0000-0000-000000000006', 'Kenji Tanaka', 'kenji.t@demo.io', 'Full-Stack Developer | Ruby on Rails & Vue.js', 'Pragmatic developer focused on shipping value fast. Strong believer in convention over configuration.', 'jp', 'Tokyo', ARRAY['Ruby', 'Rails', 'Vue.js', 'PostgreSQL', 'Redis', 'Docker', 'Heroku', 'RSpec'], 9, '[{"institution":"University of Tokyo","degree":"B.Eng","field":"Information Science","end_year":2015}]'::jsonb, '[{"company":"SmartHR","title":"Lead Developer","start_date":"2020-04","is_current":true},{"company":"Cookpad","title":"Senior Developer","start_date":"2017-01","end_date":"2020-03","is_current":false}]'::jsonb, ARRAY['Japanese', 'English'], 'citizen', ARRAY['hybrid', 'team', 'balance', 'demo'], true, 'hybrid', false),

('00000000-0000-0000-0000-000000000007', 'Olga Novikova', 'olga.n@demo.io', 'Software Engineer | Java & Spring Boot', 'Enterprise software specialist with banking domain expertise. Certified AWS Solutions Architect.', 'de', 'Berlin', ARRAY['Java', 'Spring Boot', 'Kafka', 'PostgreSQL', 'AWS', 'Microservices', 'REST APIs', 'JUnit'], 10, '[{"institution":"TU Munich","degree":"M.S.","field":"Informatics","end_year":2014}]'::jsonb, '[{"company":"N26","title":"Senior Engineer","start_date":"2019-01","is_current":true},{"company":"Deutsche Bank","title":"Software Developer","start_date":"2014-09","end_date":"2018-12","is_current":false}]'::jsonb, ARRAY['German', 'Russian', 'English'], 'permanent_resident', ARRAY['office', 'salary', 'quality', 'demo'], true, 'onsite', false),

('00000000-0000-0000-0000-000000000008', 'Carlos Ruiz', 'carlos.r@demo.io', 'Blockchain Developer | Solidity & Web3', 'DeFi builder. Audited smart contracts securing $500M+ TVL. Ex-traditional finance turned crypto native.', 'es', 'Barcelona', ARRAY['Solidity', 'TypeScript', 'Hardhat', 'Ethers.js', 'React', 'Rust', 'The Graph', 'IPFS'], 4, '[{"institution":"UPC Barcelona","degree":"M.S.","field":"Blockchain Technologies","end_year":2020}]'::jsonb, '[{"company":"Aave","title":"Smart Contract Developer","start_date":"2021-06","is_current":true},{"company":"Chainlink","title":"Junior Developer","start_date":"2020-03","end_date":"2021-05","is_current":false}]'::jsonb, ARRAY['Spanish', 'English', 'Catalan'], 'citizen', ARRAY['remote', 'autonomy', 'startup', 'demo'], true, 'remote', true),

-- ── Product ──
('00000000-0000-0000-0000-000000000009', 'Rachel Kim', 'rachel.k@demo.io', 'Senior Product Manager | B2B SaaS & Growth', 'Data-driven PM who shipped products from 0→1 and scaled to millions. Passionate about customer discovery.', 'us', 'New York', ARRAY['Product Strategy', 'A/B Testing', 'SQL', 'Figma', 'Jira', 'OKRs', 'User Research', 'Analytics'], 8, '[{"institution":"Wharton","degree":"MBA","field":"Technology Management","end_year":2016}]'::jsonb, '[{"company":"Notion","title":"Senior PM","start_date":"2021-01","is_current":true},{"company":"Intercom","title":"Product Manager","start_date":"2018-03","end_date":"2020-12","is_current":false}]'::jsonb, ARRAY['English', 'Korean'], 'citizen', ARRAY['hybrid', 'team', 'ship', 'coaching', 'demo'], true, 'hybrid', false),

('00000000-0000-0000-0000-000000000010', 'Thomas Mueller', 'thomas.m@demo.io', 'Product Lead | Platform & Developer Tools', 'Built developer platforms used by 50K+ developers. Strong technical background with engineering-to-PM transition.', 'de', 'Munich', ARRAY['Product Management', 'API Design', 'Developer Experience', 'SQL', 'Python', 'Amplitude', 'Roadmapping'], 6, '[{"institution":"TU Munich","degree":"M.S.","field":"Computer Science","end_year":2018}]'::jsonb, '[{"company":"JetBrains","title":"Product Lead","start_date":"2022-01","is_current":true},{"company":"GitHub","title":"Product Manager","start_date":"2019-06","end_date":"2021-12","is_current":false}]'::jsonb, ARRAY['German', 'English'], 'citizen', ARRAY['hybrid', 'autonomy', 'quality', 'demo'], true, 'hybrid', false),

('00000000-0000-0000-0000-000000000011', 'Maria Garcia', 'maria.g@demo.io', 'Product Owner | Fintech & Payments', 'Certified Scrum Product Owner with deep payments domain expertise. Led team delivering PSD2 compliance.', 'nl', 'Amsterdam', ARRAY['Product Ownership', 'Scrum', 'Payments', 'Compliance', 'Jira', 'Confluence', 'User Stories', 'Stakeholder Management'], 7, '[{"institution":"University of Amsterdam","degree":"M.S.","field":"Business Administration","end_year":2017}]'::jsonb, '[{"company":"Adyen","title":"Senior Product Owner","start_date":"2020-09","is_current":true},{"company":"ING","title":"Product Owner","start_date":"2017-06","end_date":"2020-08","is_current":false}]'::jsonb, ARRAY['Dutch', 'Spanish', 'English'], 'permanent_resident', ARRAY['office', 'team', 'salary', 'demo'], true, 'onsite', false),

-- ── Data & AI ──
('00000000-0000-0000-0000-000000000012', 'David Liu', 'david.l@demo.io', 'Machine Learning Engineer | NLP & LLMs', 'Building production ML systems at scale. Published 3 papers on transformer architectures. Ex-Google Brain.', 'ca', 'Toronto', ARRAY['Python', 'PyTorch', 'TensorFlow', 'NLP', 'LLMs', 'MLOps', 'Kubernetes', 'SQL'], 6, '[{"institution":"University of Toronto","degree":"Ph.D.","field":"Machine Learning","end_year":2018}]'::jsonb, '[{"company":"Cohere","title":"Senior ML Engineer","start_date":"2021-03","is_current":true},{"company":"Google Brain","title":"Research Engineer","start_date":"2018-09","end_date":"2021-02","is_current":false}]'::jsonb, ARRAY['English', 'Mandarin', 'French'], 'permanent_resident', ARRAY['remote', 'autonomy', 'quality', 'demo'], true, 'remote', true),

('00000000-0000-0000-0000-000000000013', 'Fatima Al-Rashid', 'fatima.a@demo.io', 'Data Scientist | Analytics & Experimentation', 'Turn data into decisions. Built experimentation platforms powering 1000+ A/B tests per month.', 'gb', 'London', ARRAY['Python', 'R', 'SQL', 'Spark', 'Tableau', 'A/B Testing', 'Statistics', 'dbt'], 5, '[{"institution":"Oxford University","degree":"M.S.","field":"Statistics","end_year":2019}]'::jsonb, '[{"company":"Booking.com","title":"Senior Data Scientist","start_date":"2021-06","is_current":true},{"company":"Revolut","title":"Data Scientist","start_date":"2019-09","end_date":"2021-05","is_current":false}]'::jsonb, ARRAY['English', 'Arabic'], 'work_visa', ARRAY['hybrid', 'quality', 'salary', 'demo'], true, 'hybrid', false),

('00000000-0000-0000-0000-000000000014', 'Lucas Moreau', 'lucas.m@demo.io', 'AI Engineer | Computer Vision & MLOps', 'Computer vision specialist focused on real-time inference. Deployed models processing 1M+ images daily.', 'fr', 'Paris', ARRAY['Python', 'PyTorch', 'OpenCV', 'ONNX', 'Docker', 'FastAPI', 'MLflow', 'AWS SageMaker'], 4, '[{"institution":"École Polytechnique","degree":"M.Eng","field":"Applied Mathematics","end_year":2020}]'::jsonb, '[{"company":"Hugging Face","title":"ML Engineer","start_date":"2022-01","is_current":true},{"company":"Criteo","title":"Data Scientist","start_date":"2020-06","end_date":"2021-12","is_current":false}]'::jsonb, ARRAY['French', 'English'], 'citizen', ARRAY['remote', 'startup', 'ship', 'demo'], true, 'remote', true),

-- ── Design ──
('00000000-0000-0000-0000-000000000015', 'Emma Wilson', 'emma.w@demo.io', 'Senior UX Designer | Product & Design Systems', 'Human-centered designer with a systems thinking approach. Led redesigns increasing conversion by 40%.', 'us', 'Portland', ARRAY['Figma', 'User Research', 'Prototyping', 'Design Systems', 'Accessibility', 'Information Architecture', 'Usability Testing'], 7, '[{"institution":"RISD","degree":"BFA","field":"Industrial Design","end_year":2017}]'::jsonb, '[{"company":"Airbnb","title":"Senior UX Designer","start_date":"2020-08","is_current":true},{"company":"Nike","title":"UX Designer","start_date":"2017-09","end_date":"2020-07","is_current":false}]'::jsonb, ARRAY['English'], 'citizen', ARRAY['hybrid', 'team', 'quality', 'coaching', 'demo'], true, 'hybrid', true),

('00000000-0000-0000-0000-000000000016', 'Yuki Hashimoto', 'yuki.h@demo.io', 'UI/UX Designer | Mobile & Creative Direction', 'Award-winning mobile designer. 3x Apple Design Award nominee. Strong illustration and motion design skills.', 'jp', 'Osaka', ARRAY['Figma', 'Sketch', 'After Effects', 'Principle', 'Illustration', 'Motion Design', 'iOS Design', 'Material Design'], 6, '[{"institution":"Kyoto University","degree":"M.A.","field":"Design","end_year":2018}]'::jsonb, '[{"company":"LINE","title":"Lead Designer","start_date":"2021-04","is_current":true},{"company":"Mercari","title":"UI Designer","start_date":"2018-07","end_date":"2021-03","is_current":false}]'::jsonb, ARRAY['Japanese', 'English'], 'citizen', ARRAY['hybrid', 'quality', 'balance', 'demo'], true, 'hybrid', false),

('00000000-0000-0000-0000-000000000017', 'Lena Hoffmann', 'lena.h@demo.io', 'UX Researcher | Qualitative & Quantitative Methods', 'Mixed-methods researcher passionate about inclusive design. Conducted 200+ user interviews across 15 countries.', 'de', 'Hamburg', ARRAY['User Research', 'Usability Testing', 'Survey Design', 'Data Analysis', 'Figma', 'Miro', 'Dovetail', 'Statistics'], 5, '[{"institution":"University of Hamburg","degree":"M.A.","field":"Cognitive Psychology","end_year":2019}]'::jsonb, '[{"company":"Zalando","title":"Senior UX Researcher","start_date":"2021-09","is_current":true},{"company":"SAP","title":"UX Researcher","start_date":"2019-06","end_date":"2021-08","is_current":false}]'::jsonb, ARRAY['German', 'English', 'French'], 'citizen', ARRAY['hybrid', 'team', 'coaching', 'demo'], true, 'hybrid', true),

-- ── Marketing ──
('00000000-0000-0000-0000-000000000018', 'James O''Brien', 'james.o@demo.io', 'Growth Marketing Manager | B2B SaaS', 'Full-funnel growth marketer. Scaled ARR from $2M to $20M through content-led growth and paid acquisition.', 'ie', 'Dublin', ARRAY['SEO', 'Content Marketing', 'Google Ads', 'HubSpot', 'Analytics', 'A/B Testing', 'Email Marketing', 'LinkedIn Ads'], 6, '[{"institution":"Trinity College Dublin","degree":"M.S.","field":"Digital Marketing","end_year":2018}]'::jsonb, '[{"company":"Intercom","title":"Growth Manager","start_date":"2021-01","is_current":true},{"company":"HubSpot","title":"Marketing Manager","start_date":"2018-06","end_date":"2020-12","is_current":false}]'::jsonb, ARRAY['English'], 'citizen', ARRAY['hybrid', 'team', 'ship', 'demo'], true, 'hybrid', false),

('00000000-0000-0000-0000-000000000019', 'Isabella Costa', 'isabella.c@demo.io', 'Content Marketing Lead | SEO & Brand Strategy', 'Content strategist who grew organic traffic 500% in 18 months. Storyteller at heart, data-driven by nature.', 'pt', 'Lisbon', ARRAY['Content Strategy', 'SEO', 'Copywriting', 'WordPress', 'Ahrefs', 'Google Analytics', 'Social Media', 'Brand Strategy'], 5, '[{"institution":"Nova SBE","degree":"M.S.","field":"Marketing","end_year":2019}]'::jsonb, '[{"company":"Remote.com","title":"Content Lead","start_date":"2021-03","is_current":true},{"company":"Unbabel","title":"Content Manager","start_date":"2019-06","end_date":"2021-02","is_current":false}]'::jsonb, ARRAY['Portuguese', 'English', 'Spanish'], 'citizen', ARRAY['remote', 'startup', 'quality', 'demo'], true, 'remote', true),

-- ── Finance ──
('00000000-0000-0000-0000-000000000020', 'Alexander Petrov', 'alex.p@demo.io', 'Financial Analyst | FP&A & Fundraising', 'Helped 5 startups raise $200M+ in VC funding. Expert financial modeler with investment banking background.', 'ch', 'Zurich', ARRAY['Financial Modeling', 'Excel', 'SQL', 'Tableau', 'FP&A', 'Fundraising', 'Due Diligence', 'M&A'], 8, '[{"institution":"ETH Zurich","degree":"M.S.","field":"Quantitative Finance","end_year":2016}]'::jsonb, '[{"company":"Sequoia Capital","title":"Financial Analyst","start_date":"2020-01","is_current":true},{"company":"UBS","title":"Associate","start_date":"2016-09","end_date":"2019-12","is_current":false}]'::jsonb, ARRAY['English', 'Russian', 'German'], 'permanent_resident', ARRAY['office', 'salary', 'pressure', 'demo'], true, 'onsite', false),

('00000000-0000-0000-0000-000000000021', 'Natalie Dubois', 'natalie.d@demo.io', 'CFO | Startup Finance & Operations', 'Fractional CFO for Series A-C startups. Built finance teams from scratch. IPO preparation experience.', 'fr', 'Lyon', ARRAY['Financial Planning', 'Accounting', 'GAAP', 'IFRS', 'NetSuite', 'Fundraising', 'Board Reporting', 'Tax Strategy'], 12, '[{"institution":"HEC Paris","degree":"MBA","field":"Finance","end_year":2012}]'::jsonb, '[{"company":"Freelance","title":"Fractional CFO","start_date":"2020-06","is_current":true},{"company":"BlaBlaCar","title":"VP Finance","start_date":"2016-01","end_date":"2020-05","is_current":false}]'::jsonb, ARRAY['French', 'English'], 'citizen', ARRAY['remote', 'autonomy', 'salary', 'demo'], true, 'remote', true),

-- ── Sales ──
('00000000-0000-0000-0000-000000000022', 'Ryan McCarthy', 'ryan.m@demo.io', 'Account Executive | Enterprise SaaS Sales', 'Consistent quota crusher — 150%+ attainment 4 years running. Specialize in complex enterprise deals $500K+.', 'us', 'Chicago', ARRAY['Enterprise Sales', 'Salesforce', 'Solution Selling', 'Contract Negotiation', 'Pipeline Management', 'MEDDIC', 'Cold Outreach'], 7, '[{"institution":"Northwestern","degree":"B.S.","field":"Business Administration","end_year":2017}]'::jsonb, '[{"company":"Snowflake","title":"Senior AE","start_date":"2021-06","is_current":true},{"company":"Salesforce","title":"Account Executive","start_date":"2018-01","end_date":"2021-05","is_current":false}]'::jsonb, ARRAY['English'], 'citizen', ARRAY['hybrid', 'pressure', 'salary', 'demo'], true, 'hybrid', false),

('00000000-0000-0000-0000-000000000023', 'Aisha Mohammed', 'aisha.m@demo.io', 'SDR Manager | B2B Outbound & Team Building', 'Built and scaled SDR team from 2 to 20. Pipeline generation machine — $40M+ pipeline influenced.', 'gb', 'Manchester', ARRAY['Outbound Sales', 'Team Management', 'SalesLoft', 'LinkedIn Sales Nav', 'Cold Calling', 'Coaching', 'HubSpot', 'Revenue Operations'], 5, '[{"institution":"University of Manchester","degree":"B.A.","field":"Business Studies","end_year":2019}]'::jsonb, '[{"company":"Gong","title":"SDR Manager","start_date":"2022-01","is_current":true},{"company":"Outreach","title":"Senior SDR","start_date":"2019-09","end_date":"2021-12","is_current":false}]'::jsonb, ARRAY['English', 'Arabic'], 'citizen', ARRAY['office', 'team', 'coaching', 'pressure', 'demo'], true, 'onsite', true),

-- ── People & HR ──
('00000000-0000-0000-0000-000000000024', 'Sarah Van der Berg', 'sarah.v@demo.io', 'Head of People | Scaling Culture in Remote Teams', 'Built People function from ground up at 3 startups. Expert in remote-first culture and distributed team management.', 'nl', 'Rotterdam', ARRAY['People Operations', 'Talent Acquisition', 'Culture Building', 'Compensation', 'HRIS', 'Performance Management', 'DEI', 'Employment Law'], 9, '[{"institution":"Erasmus University","degree":"M.S.","field":"HR Management","end_year":2015}]'::jsonb, '[{"company":"GitLab","title":"Head of People EMEA","start_date":"2021-01","is_current":true},{"company":"Miro","title":"People Lead","start_date":"2018-03","end_date":"2020-12","is_current":false}]'::jsonb, ARRAY['Dutch', 'English', 'German'], 'citizen', ARRAY['remote', 'team', 'coaching', 'balance', 'demo'], true, 'remote', false),

('00000000-0000-0000-0000-000000000025', 'Chen Wei', 'chen.w@demo.io', 'Talent Acquisition Lead | Tech Recruiting', 'Hired 200+ engineers across APAC and North America. Built employer brand programs doubling inbound applications.', 'cn', 'Shanghai', ARRAY['Technical Recruiting', 'Employer Branding', 'ATS', 'LinkedIn Recruiter', 'Diversity Recruiting', 'Compensation Benchmarking', 'Interview Design'], 6, '[{"institution":"Fudan University","degree":"M.A.","field":"Human Resources","end_year":2018}]'::jsonb, '[{"company":"ByteDance","title":"TA Lead","start_date":"2021-09","is_current":true},{"company":"Alibaba","title":"Senior Recruiter","start_date":"2018-06","end_date":"2021-08","is_current":false}]'::jsonb, ARRAY['Mandarin', 'English'], 'citizen', ARRAY['office', 'team', 'ship', 'demo'], true, 'onsite', false),

-- ── More Engineering (diverse countries) ──
('00000000-0000-0000-0000-000000000026', 'Nguyen Minh', 'nguyen.m@demo.io', 'Full-Stack Developer | Laravel & Vue.js', 'Building fintech solutions for Southeast Asia. Strong focus on payment integrations and compliance.', 'vn', 'Ho Chi Minh City', ARRAY['PHP', 'Laravel', 'Vue.js', 'MySQL', 'Redis', 'Docker', 'AWS', 'Payment APIs'], 5, '[{"institution":"HCMC University of Technology","degree":"B.Eng","field":"Software Engineering","end_year":2019}]'::jsonb, '[{"company":"MoMo","title":"Senior Developer","start_date":"2021-06","is_current":true},{"company":"FPT Software","title":"Developer","start_date":"2019-07","end_date":"2021-05","is_current":false}]'::jsonb, ARRAY['Vietnamese', 'English'], 'citizen', ARRAY['remote', 'ship', 'startup', 'demo'], true, 'remote', true),

('00000000-0000-0000-0000-000000000027', 'Diego Fernandez', 'diego.f@demo.io', 'Software Engineer | .NET & Azure Cloud', 'Enterprise software engineer specializing in Azure microservices and event-driven architectures.', 'ar', 'Buenos Aires', ARRAY['C#', '.NET', 'Azure', 'SQL Server', 'RabbitMQ', 'Blazor', 'Docker', 'Entity Framework'], 7, '[{"institution":"Universidad de Buenos Aires","degree":"Lic.","field":"Computer Science","end_year":2017}]'::jsonb, '[{"company":"MercadoLibre","title":"Senior Engineer","start_date":"2020-03","is_current":true},{"company":"Globant","title":"Software Developer","start_date":"2017-06","end_date":"2020-02","is_current":false}]'::jsonb, ARRAY['Spanish', 'English'], 'citizen', ARRAY['remote', 'team', 'balance', 'demo'], true, 'remote', false),

('00000000-0000-0000-0000-000000000028', 'Jakub Kowalski', 'jakub.k@demo.io', 'Backend Developer | Elixir & Distributed Systems', 'Functional programming advocate. Built real-time systems handling 500K concurrent connections.', 'pl', 'Warsaw', ARRAY['Elixir', 'Phoenix', 'PostgreSQL', 'Redis', 'Docker', 'Kubernetes', 'RabbitMQ', 'Erlang/OTP'], 6, '[{"institution":"University of Warsaw","degree":"M.S.","field":"Computer Science","end_year":2018}]'::jsonb, '[{"company":"Remote.com","title":"Senior Backend Engineer","start_date":"2021-09","is_current":true},{"company":"Allegro","title":"Backend Developer","start_date":"2018-07","end_date":"2021-08","is_current":false}]'::jsonb, ARRAY['Polish', 'English'], 'citizen', ARRAY['remote', 'autonomy', 'quality', 'demo'], true, 'remote', true),

('00000000-0000-0000-0000-000000000029', 'Rajesh Kumar', 'rajesh.k@demo.io', 'Cloud Architect | Multi-Cloud & Enterprise', 'AWS & Azure certified architect. Led cloud migration for Fortune 100 insurance company saving $15M/year.', 'in', 'Bangalore', ARRAY['AWS', 'Azure', 'GCP', 'Terraform', 'Kubernetes', 'Cloud Security', 'Architecture', 'Cost Optimization'], 12, '[{"institution":"IIT Bombay","degree":"B.Tech","field":"Computer Science","end_year":2012}]'::jsonb, '[{"company":"ThoughtWorks","title":"Principal Consultant","start_date":"2019-01","is_current":true},{"company":"Infosys","title":"Cloud Architect","start_date":"2014-06","end_date":"2018-12","is_current":false}]'::jsonb, ARRAY['English', 'Hindi', 'Kannada'], 'needs_sponsorship', ARRAY['remote', 'coaching', 'salary', 'demo'], true, 'remote', true),

('00000000-0000-0000-0000-000000000030', 'Marta Nowak', 'marta.n@demo.io', 'QA Engineer | Test Automation & CI/CD', 'Quality champion with a developer mindset. Built test frameworks reducing regression time from 8 hours to 20 minutes.', 'cz', 'Prague', ARRAY['Playwright', 'Cypress', 'TypeScript', 'Jenkins', 'Docker', 'API Testing', 'Performance Testing', 'Selenium'], 5, '[{"institution":"Charles University","degree":"M.S.","field":"Software Engineering","end_year":2019}]'::jsonb, '[{"company":"JetBrains","title":"Senior QA Engineer","start_date":"2021-04","is_current":true},{"company":"Avast","title":"QA Engineer","start_date":"2019-06","end_date":"2021-03","is_current":false}]'::jsonb, ARRAY['Czech', 'English', 'Polish'], 'citizen', ARRAY['hybrid', 'quality', 'team', 'demo'], true, 'hybrid', false),

-- ── More diverse roles ──
('00000000-0000-0000-0000-000000000031', 'Kim Soo-jin', 'kim.sj@demo.io', 'Product Designer | E-commerce & Conversion', 'Design-to-revenue thinker. My designs generated $30M+ in measurable incremental revenue through UX improvements.', 'kr', 'Seoul', ARRAY['Figma', 'Prototyping', 'E-commerce UX', 'Analytics', 'A/B Testing', 'Design Thinking', 'User Research', 'Webflow'], 6, '[{"institution":"KAIST","degree":"M.S.","field":"Industrial Design","end_year":2018}]'::jsonb, '[{"company":"Coupang","title":"Senior Product Designer","start_date":"2021-01","is_current":true},{"company":"Samsung","title":"UX Designer","start_date":"2018-06","end_date":"2020-12","is_current":false}]'::jsonb, ARRAY['Korean', 'English'], 'citizen', ARRAY['hybrid', 'ship', 'quality', 'demo'], true, 'hybrid', true),

('00000000-0000-0000-0000-000000000032', 'Marco Rossi', 'marco.r@demo.io', 'Data Engineer | Spark & Real-Time Pipelines', 'Built data platforms processing 10TB+ daily. Expert in real-time streaming and data lake architectures.', 'it', 'Milan', ARRAY['Python', 'Spark', 'Kafka', 'Airflow', 'dbt', 'Snowflake', 'AWS', 'SQL'], 7, '[{"institution":"Politecnico di Milano","degree":"M.S.","field":"Data Engineering","end_year":2017}]'::jsonb, '[{"company":"Spotify","title":"Senior Data Engineer","start_date":"2020-09","is_current":true},{"company":"Bending Spoons","title":"Data Engineer","start_date":"2017-06","end_date":"2020-08","is_current":false}]'::jsonb, ARRAY['Italian', 'English'], 'permanent_resident', ARRAY['remote', 'autonomy', 'quality', 'demo'], true, 'remote', false),

('00000000-0000-0000-0000-000000000033', 'Sofia Andersson', 'sofia.a@demo.io', 'Growth Product Manager | PLG & Activation', 'Product-led growth specialist. Improved trial-to-paid conversion by 60% through onboarding optimization.', 'dk', 'Copenhagen', ARRAY['Product Management', 'PLG', 'Analytics', 'Amplitude', 'Mixpanel', 'SQL', 'Experimentation', 'Activation'], 5, '[{"institution":"CBS Copenhagen","degree":"M.S.","field":"Business & Innovation","end_year":2019}]'::jsonb, '[{"company":"Pleo","title":"Growth PM","start_date":"2021-06","is_current":true},{"company":"Unity","title":"Product Manager","start_date":"2019-09","end_date":"2021-05","is_current":false}]'::jsonb, ARRAY['Danish', 'Swedish', 'English'], 'citizen', ARRAY['hybrid', 'startup', 'ship', 'demo'], true, 'hybrid', true),

('00000000-0000-0000-0000-000000000034', 'André Oliveira', 'andre.o@demo.io', 'Security Engineer | AppSec & Penetration Testing', 'Offensive security professional turned builder. OSCP certified. Found critical vulnerabilities in Fortune 500 apps.', 'br', 'Rio de Janeiro', ARRAY['Python', 'Burp Suite', 'OWASP', 'Kubernetes Security', 'AWS Security', 'Penetration Testing', 'Threat Modeling', 'SAST/DAST'], 6, '[{"institution":"UFRJ","degree":"M.S.","field":"Information Security","end_year":2018}]'::jsonb, '[{"company":"HackerOne","title":"Senior Security Engineer","start_date":"2021-01","is_current":true},{"company":"Nubank","title":"AppSec Engineer","start_date":"2018-06","end_date":"2020-12","is_current":false}]'::jsonb, ARRAY['Portuguese', 'English'], 'needs_sponsorship', ARRAY['remote', 'autonomy', 'quality', 'demo'], true, 'remote', true),

('00000000-0000-0000-0000-000000000035', 'Laura Dubois', 'laura.d@demo.io', 'Marketing Analytics Manager | Attribution & ROI', 'Marketing scientist bridging creative and data. Built attribution models saving $5M+ in wasted ad spend.', 'be', 'Brussels', ARRAY['Google Analytics', 'SQL', 'Python', 'Tableau', 'Google Ads', 'Meta Ads', 'Attribution Modeling', 'Marketing Mix Modeling'], 5, '[{"institution":"KU Leuven","degree":"M.S.","field":"Data Science","end_year":2019}]'::jsonb, '[{"company":"Deliverect","title":"Marketing Analytics Manager","start_date":"2021-09","is_current":true},{"company":"Proximus","title":"Marketing Analyst","start_date":"2019-06","end_date":"2021-08","is_current":false}]'::jsonb, ARRAY['French', 'Dutch', 'English'], 'citizen', ARRAY['hybrid', 'quality', 'balance', 'demo'], true, 'hybrid', false),

-- ── Additional candidates for diversity ──
('00000000-0000-0000-0000-000000000036', 'Henrik Johansson', 'henrik.j@demo.io', 'Engineering Manager | Platform Teams', 'People-first engineering leader. Grew team from 4 to 25 engineers while maintaining high delivery velocity.', 'no', 'Oslo', ARRAY['Team Leadership', 'Architecture', 'Agile', 'Hiring', 'Python', 'Kubernetes', 'System Design', 'Mentoring'], 11, '[{"institution":"NTNU","degree":"M.S.","field":"Computer Science","end_year":2013}]'::jsonb, '[{"company":"Cognite","title":"Engineering Manager","start_date":"2020-01","is_current":true},{"company":"Opera Software","title":"Tech Lead","start_date":"2016-06","end_date":"2019-12","is_current":false}]'::jsonb, ARRAY['Norwegian', 'English', 'Swedish'], 'citizen', ARRAY['hybrid', 'coaching', 'team', 'balance', 'demo'], true, 'hybrid', false),

('00000000-0000-0000-0000-000000000037', 'Catalina Popescu', 'catalina.p@demo.io', 'Frontend Developer | Angular & Performance', 'Web performance obsessive. Reduced LCP by 70% for e-commerce platform serving 5M monthly visitors.', 'ro', 'Bucharest', ARRAY['Angular', 'TypeScript', 'RxJS', 'Web Performance', 'PWA', 'Node.js', 'Jest', 'Lighthouse'], 4, '[{"institution":"University of Bucharest","degree":"B.S.","field":"Computer Science","end_year":2020}]'::jsonb, '[{"company":"UiPath","title":"Frontend Developer","start_date":"2021-03","is_current":true},{"company":"eMAG","title":"Junior Developer","start_date":"2020-06","end_date":"2021-02","is_current":false}]'::jsonb, ARRAY['Romanian', 'English', 'French'], 'citizen', ARRAY['hybrid', 'ship', 'quality', 'demo'], true, 'hybrid', true),

('00000000-0000-0000-0000-000000000038', 'Miguel Torres', 'miguel.t@demo.io', 'iOS Developer | Swift & SwiftUI', 'Apple ecosystem specialist. 8 apps on the App Store with 2M+ total downloads. WWDC scholar.', 'mx', 'Mexico City', ARRAY['Swift', 'SwiftUI', 'Combine', 'Core Data', 'UIKit', 'Xcode', 'TestFlight', 'App Store Optimization'], 5, '[{"institution":"ITESM","degree":"B.S.","field":"Computer Science","end_year":2019}]'::jsonb, '[{"company":"Rappi","title":"iOS Lead","start_date":"2021-06","is_current":true},{"company":"Clip","title":"iOS Developer","start_date":"2019-09","end_date":"2021-05","is_current":false}]'::jsonb, ARRAY['Spanish', 'English'], 'citizen', ARRAY['remote', 'startup', 'ship', 'demo'], true, 'remote', true),

('00000000-0000-0000-0000-000000000039', 'Sari Mäkinen', 'sari.m@demo.io', 'Product Manager | Health Tech & Regulatory', 'PM at the intersection of health and technology. Navigated FDA and CE mark approvals for digital health products.', 'fi', 'Helsinki', ARRAY['Product Management', 'Health Tech', 'Regulatory Compliance', 'User Research', 'Agile', 'HIPAA', 'CE Marking', 'Clinical Workflows'], 7, '[{"institution":"Aalto University","degree":"M.S.","field":"Health Technology","end_year":2017}]'::jsonb, '[{"company":"Oura","title":"Senior PM","start_date":"2021-01","is_current":true},{"company":"Nokia Health","title":"Product Manager","start_date":"2017-06","end_date":"2020-12","is_current":false}]'::jsonb, ARRAY['Finnish', 'English', 'Swedish'], 'citizen', ARRAY['hybrid', 'quality', 'balance', 'demo'], true, 'hybrid', false),

('00000000-0000-0000-0000-000000000040', 'Juan Reyes', 'juan.r@demo.io', 'DevRel & Developer Advocate | APIs & Communities', 'Built developer communities of 50K+ members. Speaker at 30+ conferences. Technical writer with 100K+ readers.', 'es', 'Madrid', ARRAY['Technical Writing', 'Public Speaking', 'Developer Relations', 'APIs', 'JavaScript', 'Community Building', 'Content Creation', 'Video Production'], 5, '[{"institution":"UPM Madrid","degree":"B.S.","field":"Telecommunications Engineering","end_year":2019}]'::jsonb, '[{"company":"Vercel","title":"Developer Advocate","start_date":"2022-01","is_current":true},{"company":"Twilio","title":"DevRel Engineer","start_date":"2019-09","end_date":"2021-12","is_current":false}]'::jsonb, ARRAY['Spanish', 'English', 'Portuguese'], 'citizen', ARRAY['remote', 'team', 'ship', 'demo'], true, 'remote', true),

-- ── More senior / specialized profiles ──
('00000000-0000-0000-0000-000000000041', 'Daniel Fischer', 'daniel.f@demo.io', 'VP of Engineering | Scale-Up Leadership', 'Built and led 100+ person engineering org through Series B to IPO. Expert in organizational design.', 'at', 'Vienna', ARRAY['Engineering Leadership', 'Organizational Design', 'OKRs', 'Technical Strategy', 'Hiring', 'M&A Integration', 'Architecture Review', 'Board Presentations'], 15, '[{"institution":"TU Wien","degree":"Ph.D.","field":"Computer Science","end_year":2009}]'::jsonb, '[{"company":"Bitpanda","title":"VP Engineering","start_date":"2020-06","is_current":true},{"company":"Runtastic","title":"Director of Engineering","start_date":"2015-01","end_date":"2020-05","is_current":false}]'::jsonb, ARRAY['German', 'English'], 'citizen', ARRAY['hybrid', 'coaching', 'salary', 'demo'], true, 'hybrid', false),

('00000000-0000-0000-0000-000000000042', 'Grace Tan', 'grace.t@demo.io', 'Senior Data Analyst | Business Intelligence', 'Turn complex datasets into actionable business insights. Built self-serve analytics platforms for 500+ users.', 'ph', 'Manila', ARRAY['SQL', 'Python', 'Tableau', 'Power BI', 'dbt', 'BigQuery', 'Statistics', 'Excel'], 4, '[{"institution":"Ateneo de Manila","degree":"B.S.","field":"Applied Mathematics","end_year":2020}]'::jsonb, '[{"company":"Canva","title":"Senior Data Analyst","start_date":"2022-01","is_current":true},{"company":"GCash","title":"Data Analyst","start_date":"2020-06","end_date":"2021-12","is_current":false}]'::jsonb, ARRAY['Filipino', 'English'], 'needs_sponsorship', ARRAY['remote', 'team', 'balance', 'demo'], true, 'remote', true),

('00000000-0000-0000-0000-000000000043', 'Pierre Martin', 'pierre.m@demo.io', 'SRE | Reliability & Incident Management', 'Keep systems running at scale. Reduced MTTR by 80% through observability investments and runbook automation.', 'fr', 'Toulouse', ARRAY['Linux', 'Kubernetes', 'Prometheus', 'Grafana', 'Python', 'Terraform', 'PagerDuty', 'Incident Management'], 7, '[{"institution":"INSA Toulouse","degree":"M.Eng","field":"Computer Science","end_year":2017}]'::jsonb, '[{"company":"Datadog","title":"Senior SRE","start_date":"2020-09","is_current":true},{"company":"OVHcloud","title":"SRE","start_date":"2017-06","end_date":"2020-08","is_current":false}]'::jsonb, ARRAY['French', 'English'], 'citizen', ARRAY['remote', 'autonomy', 'quality', 'demo'], true, 'remote', false),

('00000000-0000-0000-0000-000000000044', 'Hannah Brown', 'hannah.b@demo.io', 'Head of Design | B2B Product Design', 'Design leader scaling teams and design systems. Championed accessibility-first design at enterprise level.', 'ca', 'Vancouver', ARRAY['Design Leadership', 'Design Systems', 'Figma', 'Accessibility', 'User Research', 'Design Ops', 'Hiring', 'Mentoring'], 10, '[{"institution":"Emily Carr University","degree":"BFA","field":"Interaction Design","end_year":2014}]'::jsonb, '[{"company":"Shopify","title":"Head of Design","start_date":"2021-01","is_current":true},{"company":"Hootsuite","title":"Design Director","start_date":"2017-06","end_date":"2020-12","is_current":false}]'::jsonb, ARRAY['English', 'French'], 'citizen', ARRAY['hybrid', 'coaching', 'team', 'quality', 'demo'], true, 'hybrid', false),

('00000000-0000-0000-0000-000000000045', 'Viktor Novak', 'viktor.n@demo.io', 'Embedded Systems Engineer | IoT & Firmware', 'Firmware engineer bridging hardware and software. Shipped IoT devices deployed in 50+ countries.', 'cz', 'Brno', ARRAY['C', 'C++', 'Embedded Linux', 'RTOS', 'BLE', 'Zigbee', 'PCB Design', 'Hardware Debugging'], 8, '[{"institution":"Brno University of Technology","degree":"M.S.","field":"Embedded Systems","end_year":2016}]'::jsonb, '[{"company":"Y Soft","title":"Senior Firmware Engineer","start_date":"2020-01","is_current":true},{"company":"Honeywell","title":"Embedded Developer","start_date":"2016-06","end_date":"2019-12","is_current":false}]'::jsonb, ARRAY['Czech', 'English', 'Slovak'], 'citizen', ARRAY['office', 'quality', 'autonomy', 'demo'], true, 'onsite', false)

ON CONFLICT DO NOTHING;
